name: Full Project CI - Complete Linting & Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  # Permitir ejecución manual
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front_nuevo
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: front_nuevo/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting and formatting
      run: |
        npm run format:check
        npm run lint
        
    - name: Build project
      run: npm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back_cheona_nuevo
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: back_cheona_nuevo/requirements.txt
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run comprehensive linting
      run: |
        echo "Running Black..."
        black --check --diff . || echo "Black found formatting issues"
        
        echo "Running isort..."
        isort --check-only --diff . || echo "isort found import sorting issues"
        
        echo "Running Flake8..."
        flake8 . || echo "Flake8 found linting issues"
        
        echo "Running Bandit (security)..."
        bandit -r . || echo "Bandit found security issues"
      continue-on-error: true

  # Job que solo pasa si ambos frontend y backend pasan
  integration:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
    - name: Integration success
      run: echo "Both frontend and backend linting passed!"
